GOTOWE!
EwaTym/InnovativeCars pull request #2
Opened 2021-06-02 14:22 UTC by EwaTym

Zapraszam do review.

2021-06-09 06:09 UTC, AdrianDlu requested changes

2021-06-09 06:09 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +            for(Salon__c s: [SELECT id, (SELECT id FROM Cars__r) FROM Salon__c WHERE id IN :salonsToClose]){
bad variable name

2021-06-09 06:09 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +    Set<String> ids= new Set<String>();
bad variable name

2021-06-09 06:09 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +        else if(oldCarMap.get(newOffer.Car__c)>1){
Jezeli oldCarMap.containsKey(newOffer.Car__c) = false to oldCarMap.get(newOffer.Car__c) zwraca null jaki jest wynik działania null >1?

2021-06-09 08:13 UTC, EwaTym commented on force-app/main/default/classes/CarHandler.cls
> +            for(Telemetry__c t: [SELECT id, Car__c FROM Telemetry__c WHERE Car__c IN :outListOfCars]){
Aby zbierał mi do listy telemetrie do usunięcia.

2021-06-09 08:14 UTC, EwaTym commented on force-app/main/default/classes/CarHandler.cls
> +               if(t!=null){
Dodana obsługa nulla

2021-06-09 08:14 UTC, EwaTym commented on force-app/main/default/classes/CarHandler.cls
> +            List<Telemetry__c> telemetriesToDML = new List<Telemetry__c>(telemetriesToDelete);
Co to znaczy dekorować listę?

2021-06-09 08:21 UTC, EwaTym commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +        else if(oldCarMap.get(newOffer.Car__c)>1){
dodana obsługa null

2021-06-09 08:23 UTC, EwaTym commented
Dodałam zmiany oprócz dekorowania listy :)

2021-06-10 05:28 UTC, AdrianDlu requested changes

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +            Decimal numOfSpacesLeft = salon.Number_of_spaces__c - salon.Cars__r.size();
format (brak wciecia)

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +                }
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +              insert casesToAdd;
format z kad te wciecie?

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarOfferTest.cls
> +        for(Database.SaveResult r : result){
bad variable name r

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarOfferTest.cls
> +        for(Database.SaveResult r : result){
bad variable name

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarOfferTest.cls
> +            System.assert(!r.isSuccess());
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +    for(Database.DeleteResult r : result){
var name

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +    System.assert(r.isSuccess());
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +    for(Database.DeleteResult r : result){
var name

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +    for(Database.SaveResult r : result){
var name

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +        }
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +    for(Database.SaveResult r : result){
var name

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +        }
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls
> +        }
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +        oldCarMap.put(oldOffer.Car__c, 0);
format

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +        else if(oldCarMap.get(newOffer.Car__c)>1){
dead code do tego ifa nigdy nie uda ci sie wejsc. Jak testujesz ta logike manualnie i w unit testach?

2021-06-10 05:28 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +            }
format

2021-06-10 08:39 UTC, EwaTym commented
Poprawione!

2021-06-10 12:52 UTC, AdrianDlu requested changes
Ładnie zformatowane :)

2021-06-10 12:52 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +        System.debug(PRIVATE_STR_CANT_BE_TWO);
Debugi z loging levelem

2021-06-10 12:52 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +  System.debug(newCarMap);
logging level

2021-06-10 12:52 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +      System.debug(PRIVATE_STR_NULL);
LL

2021-06-10 12:52 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +      System.debug(PRIVATE_STR_ONE_CAR);
LL

2021-06-10 12:52 UTC, AdrianDlu commented on force-app/main/default/triggers/CarOfferTrigger.trigger
> +    } else if (oldCarMap.containsKey(newOffer.Car__c)) {
Czy potrzebny if?

2021-06-11 06:09 UTC, AdrianDlu approved these changes

2021-06-11 06:09 UTC, merged