Zadanie 5 gotowe async
EwaTym/InnovativeCars pull request #6
Opened 2021-06-11 12:03 UTC by EwaTym

2021-06-14 06:08 UTC, AdrianDlu requested changes

2021-06-14 06:08 UTC, AdrianDlu commented on force-app/main/default/classes/CarOfferTest.cls
> +    Test.stopTest();
missing assert

2021-06-14 06:08 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +    for (Salon__c s : [
Co to za regresja? Przejzalas swoj pull req?

2021-06-14 06:08 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +  public static void prepareRenovationCase(List<Salon__c> outlistOfNewSalon) {
Ta metoda wykonuje sie w trigerze a przeciez w zadaniu mialo byc by nie ociazac tranzakcji wiec ta metoda nie moze byc synchroniczna

2021-06-14 06:08 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +    if (!test.isRunningTest()) {
Gdybs pozniej chciala zrobic tu CC to bedzie niemozliwe przez ten zapis moze lepiej przeniesc go do lini 137?

2021-06-14 06:08 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +          System.debug('Udalo sie');
LL

2021-06-14 18:41 UTC, EwaTym commented
Gotowe do review

2021-06-15 06:14 UTC, AdrianDlu requested changes

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/BatchTest.cls
> +  static void testBatch() {
jdock

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/CarOfferTest.cls
> +    Test.stopTest();
System.assert(true); :) tu mozesz zrobic bardziej sensowny test np cos z tej klasy https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_limits.htm

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/DeleteTelemetryBatch.cls
> +    //if(!Test.isRunningTest()){
nie zostawiaj zakomentowanego kodu

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonHandler.cls
> +    for (Salon__c s : [
#Ignored!

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +  List<Salon__c> salons;
To jest zmienna publiczna prywatna gdzie sa kwantyfikatory dostepu?

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +    for (Salon__c s : salons) {
bad variable name

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +      requestRenovationTeam(casesId);
[INFO] Futur z Queueable  to chyba raczej bad practice. To wlasnie Queueable ma mozliwosc chainowania zadan wiec niema sensu mieszac tych 2 technologi

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +    for (Case c : [
bad variable name

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +        c.Status = 'Closed';
hardcode

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +        c.Status = 'Failed';
hardcode

2021-06-15 06:14 UTC, AdrianDlu commented on force-app/main/default/classes/ScheduleTelemetryDelete.cls
> +    Id batchId = Database.executeBatch(myBatchObject);
po co ci zmienna batchId?

2021-06-15 08:22 UTC, EwaTym commented
Poprawione

2021-06-16 06:28 UTC, AdrianDlu commented on force-app/main/default/classes/SalonRenovation.cls
> +  public static void requestRenovationTeam(List<Id> casesId) {
usunelas futur? czy to działa?

2021-06-16 11:53 UTC, AdrianDlu commented on force-app/main/default/classes/ScheduleTelemetryDelete.cls
> +  // }
Nie zostawiaj zakomentowanego koidu i czemu to usuwasz?

2021-06-16 12:25 UTC, EwaTym commented on force-app/main/default/classes/ScheduleTelemetryDelete.cls
> +  // }
Ajjjj!!! juz zmieniam, usuwam bo to była metoda tylko rozpoczęcia schedulera, i tak sie dziwiłam, że nie testuje mi tej metody zwykły test schedulera :)

2021-06-16 12:57 UTC, AdrianDlu approved these changes

2021-06-16 12:57 UTC, merged