Rest Gotowe
EwaTym/InnovativeCars pull request #7
Opened 2021-06-16 18:18 UTC by EwaTym

2021-06-17 08:56 UTC, AdrianDlu requested changes

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/AccountRest.cls
> +    List<Account> accounts = [SELECT Id, Name FROM Account];
po co ci zmienna request i accounts?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutToOtherSalonTest.cls
> +  public static void TestsetInterestOnCar() {
Nazwa metody z duzej litery? I nie camelCasem?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutToOtherSalonTest.cls
> +  static void TestgetAccounts() {
Nazwa metody z duzej litery? I nie camelCasem?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutToOtherSalonTest.cls
> +  static void TestgetSalonsForAccount() {
Popraw nazwy metod

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutToOtherSalonTest.cls
> +    HttpResponse result = CalloutsToOtherSalon.setInterestOnCar(
czy czasem callouty nie musza byc w test.start/stop?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +  static final String PRIVATE_STR_AUTHORIZATION = 'Authorization';
kwantyfikator dostepu?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +  public static HttpResponse setInterestOnCar(String Id) {
Zla nazwa parametru brak prefixu i nazwa zmiennej taka sama jak nazwa typu :(

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      accessToken = ReturnAccesToken.returnAccessToken();
Nazwa klasy taka sama jak nazwa metody?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response.getBody());
debug z logging levelem

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response.getBody());
LL

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +  public static List<SalonWrapper> getSalonsForAccount(String Id) {
parametr

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response.getBody());
LL

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +  public static List<CarWrapper> getCarsForSalon(String Id) {
param

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response.getBody());
LL

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +    List<Car__c> outListOfCars
jak to out? chyba in

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +    HttpResponse response = http.send(request);
zadnej obslugi czy sie udalo czy nie ? moze debug

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +  public static void createNewCaseAfterDelete(List<Car__c> outListOfCars) {
public? out?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CarIntrestRestManager.cls
> +    Car__c car = [
Co sie stanie jak bedzie zle id?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CarTest.cls-meta.xml
> +<?xml version="1.0" encoding="UTF-8"?>
??

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CarWrapper.cls
> +    String outCarMake,
out?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/GetAccountsMock.cls
> +global class GetAccountsMock implements HttpCalloutMock {
Ile potrzeba class mockowych? Czym one sie od siebie roznia?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/GetAccountsMock.cls
> +  public static final String PRIVATE_STR_CONTENT_TYPE = 'Content-Type';
Moze lepiej przeniesc do constantow ile masz takich samych content typow?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/ReturnAccesToken.cls
> +  public static String returnAccessToken() {
[INFO]Singleton byłby fajny nie sądzisz?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/SalonWrapper.cls
> +  global SalonWrapper(String outName, String outId) {
out?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/TestDataFactory.cls
> +    List<Account> accs,
in?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/TestDataFactory.cls
> +  public static List<Salon__c> createThreeSalonsPerAccount(List<Account> accs) {
in?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/TestDataFactory.cls
> +  public static List<CarWrapper> createCarWrapper(List<Car__c> cars) {
in?

2021-06-17 08:56 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +  public static void decideSendOrUtilizeCar(List<Car__c> outListOfCars) {
out?

2021-06-18 06:39 UTC, AdrianDlu requested changes

2021-06-18 06:39 UTC, AdrianDlu commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response);
LL

2021-06-18 06:39 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +  public static void createNewCaseAfterDelete(List<Car__c> inListOfCars) {
Public? #Ignored!

2021-06-18 06:39 UTC, AdrianDlu commented on force-app/main/default/classes/CarIntrestRestManager.cls
> +    Car__c car = [
#Ignored!

2021-06-18 06:39 UTC, AdrianDlu commented on force-app/main/default/classes/CarHandler.cls
> +  public static void decideSendOrUtilizeCar(List<Car__c> outListOfCars) {
#Ignored!

2021-06-18 08:36 UTC, EwaTym commented on force-app/main/default/classes/CalloutsToOtherSalon.cls
> +      System.debug(response);
wcześniej mówiłeś żeby zrobić tu debuga

2021-06-21 06:12 UTC, AdrianDlu commented
Rozwiaz konflikty

2021-06-24 09:52 UTC, AdrianDlu approved these changes

2021-06-24 09:52 UTC, merged